{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kinitiras-webhook.labels" . | nindent 4 }}
  name: {{ include "kinitiras-webhook.fullname" . }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
{{- end }}