apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kinitiras-webhook.fullname" . }}
  annotations:
    # ignore out of sync status for secret
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""