apiVersion: v1
kind: Service
metadata:
  name: {{ include "kinitiras-webhook.fullname" . }}
  labels:
    {{- include "kinitiras-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: webhook
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      name: metrics
  selector:
    {{- include "kinitiras-webhook.selectorLabels" . | nindent 4 }}
